# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AgentBrain < Formula
  desc "Invisible cross-machine sync for AI coding agents' per-project memory"
  homepage "https://github.com/Sawmonabo/agent-brain"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Sawmonabo/agent-brain/releases/download/v1.0.0/agent-brain_1.0.0_darwin_amd64.tar.gz"
      sha256 "e6401150207ebb07bb299a536ff2e9f1db126290dd57019b9563397f76753edf"

      define_method(:install) do
        bin.install "agent-brain"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Sawmonabo/agent-brain/releases/download/v1.0.0/agent-brain_1.0.0_darwin_arm64.tar.gz"
      sha256 "258351dbe69d79788439029ad39865f0f2390943e1407d1bcd1fbec5c64c13fd"

      define_method(:install) do
        bin.install "agent-brain"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Sawmonabo/agent-brain/releases/download/v1.0.0/agent-brain_1.0.0_linux_amd64.tar.gz"
      sha256 "f8f46dbbe55180260d0dcf0458966d79b96826ad52354ec94132a21ca389bb38"
      define_method(:install) do
        bin.install "agent-brain"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Sawmonabo/agent-brain/releases/download/v1.0.0/agent-brain_1.0.0_linux_arm64.tar.gz"
      sha256 "867044aca58210479d0c27098791c63fab31060f69298e01901caa8c536a7bb6"
      define_method(:install) do
        bin.install "agent-brain"
      end
    end
  end

  test do
    system "#{bin}/agent-brain", "--version"
  end
end
