# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AgentBrain < Formula
  desc "Invisible cross-machine sync for AI coding agents' per-project memory"
  homepage "https://github.com/Sawmonabo/agent-brain"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Sawmonabo/agent-brain/releases/download/v1.0.0/agent-brain_1.0.0_darwin_amd64.tar.gz"
      sha256 "5a806cb92085dad80f686e94fcfe6ec4aad61525ae7b314cc7b26ea60c81e84b"

      define_method(:install) do
        bin.install "agent-brain"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Sawmonabo/agent-brain/releases/download/v1.0.0/agent-brain_1.0.0_darwin_arm64.tar.gz"
      sha256 "a0b52ba16a5a07c0e9fb62c5291df29b618531100cd4dbb955d8fbe5e0189731"

      define_method(:install) do
        bin.install "agent-brain"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Sawmonabo/agent-brain/releases/download/v1.0.0/agent-brain_1.0.0_linux_amd64.tar.gz"
      sha256 "a9324db46a1c7812fae911273dc1be6f57813cd850ab6c7d3f4d3cac8517d670"
      define_method(:install) do
        bin.install "agent-brain"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Sawmonabo/agent-brain/releases/download/v1.0.0/agent-brain_1.0.0_linux_arm64.tar.gz"
      sha256 "a0cf3295c24907a1977a0559bc5e795de610af42734206fb138f64e0eb94493d"
      define_method(:install) do
        bin.install "agent-brain"
      end
    end
  end

  test do
    system "#{bin}/agent-brain", "--version"
  end
end
