# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AgentBrain < Formula
  desc "Invisible cross-machine sync for AI coding agents' per-project memory"
  homepage "https://github.com/Sawmonabo/agent-brain"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Sawmonabo/agent-brain/releases/download/v1.0.0/agent-brain_1.0.0_darwin_amd64.tar.gz"
      sha256 "459913f82e3100ec362bd916a8414f37bc68cece3ecf9e2bdb8e5cfff33be121"

      define_method(:install) do
        bin.install "agent-brain"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Sawmonabo/agent-brain/releases/download/v1.0.0/agent-brain_1.0.0_darwin_arm64.tar.gz"
      sha256 "882d1ba3df67af3fbbd6ca9551eadb08fce79dbb9f3eb374232d66af98a0478f"

      define_method(:install) do
        bin.install "agent-brain"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Sawmonabo/agent-brain/releases/download/v1.0.0/agent-brain_1.0.0_linux_amd64.tar.gz"
      sha256 "6a96923e56bcebf5743199441d696779d9db590c73af5d37bafa814e87d3d516"
      define_method(:install) do
        bin.install "agent-brain"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Sawmonabo/agent-brain/releases/download/v1.0.0/agent-brain_1.0.0_linux_arm64.tar.gz"
      sha256 "de71d8d1b3d861b9c7e592503b1cf6683d9a516fc1a78cff655f7cf6048da563"
      define_method(:install) do
        bin.install "agent-brain"
      end
    end
  end

  test do
    system "#{bin}/agent-brain", "--version"
  end
end
